<h1> <b> Lab - 1 </b> </h1>
<h2> Exercise on NumPy </h2>

In [1]:
import numpy as np

In [2]:
# want to import files from drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


<h2> <b> Q.1) Create a Numpy array of size 4 x 5. </b> </h2>

In [3]:
# matrix is of size 4 X 5

matrix1 = np.zeros(shape=(4,5))
print(matrix1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h2> <b> Q.2) Randomly initialize the array. </b> </h2>

In [4]:
# Initializing the matrix1

matrix1 = np.append([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [-1, 0, 4, 3, 5]], [[2, 4, -3, 0, 1]], axis=0)
print(matrix1)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [-1  0  4  3  5]
 [ 2  4 -3  0  1]]


<h2> <b> Q.3) Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant. </b> </h2>

In [5]:
# transpose of the matrix
transpose = matrix1.T
print(transpose, "\n")

square_matrix = np.zeros(shape=(3,3))
square_matrix = np.append([[1, 0, 1], [9, 5, 2]], [[-1, 7, 4]], axis=0)
print(square_matrix)

# determinant of the square matrix
det = np.linalg.det(square_matrix)
print("\nDeterminant of square matrix is: ", int(det))

[[ 1  2 -1  2]
 [ 2  3  0  4]
 [ 3  4  4 -3]
 [ 4  5  3  0]
 [ 5  6  5  1]] 

[[ 1  0  1]
 [ 9  5  2]
 [-1  7  4]]

Determinant of square matrix is:  74


<h2> <b> Q.4) Create another matrix of size 5 x 4 and randomly initialize it. </b> </h2>

In [6]:
# matrix is of size 5 X 4
matrix2 = np.zeros(shape=(5, 4))
print(matrix2, "\n")

# Initializing the matrix2
matrix2 = np.append([[2, 0, -3, 2], [2, 0, 1, -1], [1, 0, 2, 1], [-1, 0, 2, 1]], [[2, 0, -1, 1]], axis=0)
print(matrix2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[ 2  0 -3  2]
 [ 2  0  1 -1]
 [ 1  0  2  1]
 [-1  0  2  1]
 [ 2  0 -1  1]]


<h2> <b> Q.5) Perform Matrix multiplication. </b> </h2>

In [9]:
# matrix multiplication
result = np.dot(matrix1, matrix2)
print(result)

[[15  0  8 12]
 [21  0  9 16]
 [ 9  0 12 10]
 [11  0 -9 -2]]


<h2> <b> Q.6) Perform element wise matrix multiplication. </b> </h2>

In [10]:
# element wise multiplication
m1 = np.array([[1, 2], [3,1], [6,2]])
m2 = np.array([[2, 1], [0, -5], [3, 5]])
print(m1 * m2)

[[ 2  2]
 [ 0 -5]
 [18 10]]


<h2> <b> Q.7) Find mean, median of the numpy array created. </b> </h2>

In [13]:
# using matrix1 that is already declared

mean = np.mean(matrix1)
print("Mean: ",mean, "\n")

median = np.median(matrix1)
print("Meadian: ", median)

Mean:  2.5 

Meadian:  3.0


<h2> <b> Q.8) Obtain each row in the second column of the first array. </b> </h2>

In [15]:
# using matrix1 that is already declared
print(matrix1[:, 1])


[2 3 0 4]


<h2> <b> Q.9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version </b> </h2>

In [16]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/ML LAB/Iris.csv")

res = df.to_numpy()
res = res[:, :5]

# mean centered by column
nparrayCentered = res - np.mean(res, axis=0)
# print(nparrayCentered)

# verification
print(nparrayCentered.mean()) 
# -1.1256181172332921e-15 equivalent to zero(0).

-1.1256181172332921e-15


<h2> <b> Q.10) Study about numpy array attributes and implement it on the first matrix. </b> </h2>

In [18]:
# here I am using matrix1 that has declared

# 'shape' attribute
# used to get the dimension of the matrix
print("Dimension of matrix1 is: ", matrix1.shape)

# 'itemsize' attribute
# used to get length of the elements of the array in bytes
print("Itemsize of matrix1 is: ", matrix1.itemsize)

# 'ndim' attribute
# used to get the number of array dimensions
# here in ouput is 2 because of 2D array
print("Number of array dimension of matrix1 is: ", matrix1.ndim)

Dimension of matrix1 is:  (4, 5)
Itemsize of matrix1 is:  8
Number of array dimension of matrix1 is:  2
