<h1> <b> Lab - 2 </b> </h1>
<h2> <b> Excersise on Handling Categorical Data </b> </h1>
<br/>


In [1]:
# Step 1: Import Libraries

import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# step - 2 Load data

datasets = pd.read_csv("/content/drive/MyDrive/ML LAB/Exercise-CarData.csv")

print("\nDatasets: \n", datasets)
print("\n Statstics: \n", datasets.describe())


Datasets: 
       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

 Statstics: 
         Unnamed: 0         Price  ...           CC      Weight
count  

In [3]:
# Step 3: Seprate Input and Output attributes

# all rows and all cols except first
X = datasets.loc[:, datasets.columns != "Price"].values

# take only output column
Y = datasets.loc[:, datasets.columns == "Price"].values


print("Input: \n", X)
print("\n\nOutput: \n", Y)

Input: 
 [[0 23.0 '46986' ... 2000 'three' 1165]
 [1 23.0 '72937' ... 2000 '3' 1165]
 [2 24.0 '41711' ... 2000 '3' 1165]
 ...
 [1433 nan '17016' ... 1300 '3' 1015]
 [1434 70.0 '??' ... 1300 '3' 1015]
 [1435 76.0 '1' ... 1600 '5' 1114]]


Output: 
 [[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]


<br/>

<h3> <b> Handling categorical data operation on 'FuelType' column.  </b> </h3>

*   Select a column 'FuelType' from datasets and assigned to new_x.
*   Create a label encoder and transform the new_x.
*   Replace null values with 'Petrol'.
*   Assign the data of 'FuelType' to dummy and remove column.
*   Concatenate dummy and datasets to make new datasets.
*   Use onehotencoder to convert into categorical data.

<br/>

In [4]:
new_x = datasets.iloc[:, 4]

le = LabelEncoder()
new_x = le.fit_transform(new_x)

print(new_x)

datasets['FuelType'] = datasets['FuelType'].fillna('Petrol')
datasets['FuelType']

[1 1 1 ... 2 3 2]


0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...  
1431    Petrol
1432    Petrol
1433    Petrol
1434    Petrol
1435    Petrol
Name: FuelType, Length: 1436, dtype: object

In [5]:
dummy = pd.get_dummies(datasets['FuelType'])
print("\n\nDummy :\n",dummy)

datasets.drop(['FuelType'], axis = 1)
datasets = pd.concat([dummy,datasets],axis = 1)
print("\n\nFinal Data :\n",datasets)



Dummy :
       CNG  Diesel  Petrol
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0
...   ...     ...     ...
1431    0       0       1
1432    0       0       1
1433    0       0       1
1434    0       0       1
1435    0       0       1

[1436 rows x 3 columns]


Final Data :
       CNG  Diesel  Petrol  Unnamed: 0  ...  Automatic    CC  Doors Weight
0       0       1       0           0  ...          0  2000  three   1165
1       0       1       0           1  ...          0  2000      3   1165
2       0       1       0           2  ...          0  2000      3   1165
3       0       1       0           3  ...          0  2000      3   1165
4       0       1       0           4  ...          0  2000      3   1170
...   ...     ...     ...         ...  ...        ...   ...    ...    ...
1431    0       0       1        1431  ...          0  1300      3   1025
1432    0       0       1        1432  ...  

In [6]:
#Use One Hot Encoder from scikit learn
onehotencoder = OneHotEncoder()

x = onehotencoder.fit_transform(datasets.FuelType.values.reshape(-1,1)).toarray()

x

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [7]:
print(x.shape[1])
# print(x.shape)
cols = []
for i in range(x.shape[1]):
  cols.append('FuelType' + str(int(i)))
print(cols)


3
['FuelType0', 'FuelType1', 'FuelType2']


In [8]:
dfOneHot = pd.DataFrame(x, columns = cols) 
df = pd.concat([datasets, dfOneHot], axis=1) #column
#droping the country column 
df= df.drop(['FuelType'], axis=1) 
#printing to verify 
print(df.head())

   CNG  Diesel  Petrol  Unnamed: 0  ...  Weight  FuelType0 FuelType1 FuelType2
0    0       1       0           0  ...    1165        0.0       1.0       0.0
1    0       1       0           1  ...    1165        0.0       1.0       0.0
2    0       1       0           2  ...    1165        0.0       1.0       0.0
3    0       1       0           3  ...    1165        0.0       1.0       0.0
4    0       1       0           4  ...    1170        0.0       1.0       0.0

[5 rows x 16 columns]
