<h1> <b> Lab - 2 </b> </h1>
<h2> <b> Excersise on Handling Missing Values </b> </h1>
<br/>


In [54]:
# Step 1: Import Libraries

import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 

# mount drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [55]:
# step - 2 Load data

datasets = pd.read_csv("/content/drive/MyDrive/ML LAB/Exercise-CarData.csv")

print("\nDatasets: \n", datasets)
print("\n Statstics: \n", datasets.describe())


Datasets: 
       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

 Statstics: 
         Unnamed: 0         Price  ...           CC      Weight
count  

In [56]:
# Step 3: Seprate Input and Output attributes

# all rows and all cols except first
X = datasets.loc[:, datasets.columns != "Price"].values

# take only output column
Y = datasets.loc[:, datasets.columns == "Price"].values

print("Input: \n", X)
print("\n\nOutput: \n", Y)

Input: 
 [[0 23.0 '46986' ... 2000 'three' 1165]
 [1 23.0 '72937' ... 2000 '3' 1165]
 [2 24.0 '41711' ... 2000 '3' 1165]
 ...
 [1433 nan '17016' ... 1300 '3' 1015]
 [1434 70.0 '??' ... 1300 '3' 1015]
 [1435 76.0 '1' ... 1600 '5' 1114]]


Output: 
 [[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]


<br/>
 <h3><b> In handling the Price </b></h3>

*   First, we check null values are present or not.
*   In this case, null values are not present.

<br/>

In [57]:
# handling price

print(datasets['Price'].isna().sum())

# answer is zero means no null value.

0


<br/>
 <h3><b> In handling the age </b></h3>

*   First, we check null values are present or not.
*   In this case, null values are present. So, we replace it by mean of the entire column.

<br/>

In [58]:
# handling age

datasets['Age'].unique()

array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., nan, 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 55., 48., 52., 49., 56., 50.,
       47., 46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57.,
       63., 73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [59]:
#replace nan with mean value

# skipna = True ---> skip while calculating the mean
# inplace = True ---> because we are not assigning result on the left side.

datasets['Age'].fillna(datasets['Age'].mean(skipna = True), inplace = True)
datasets['Age'].unique()

array([23.        , 24.        , 26.        , 30.        , 32.        ,
       27.        , 25.        , 22.        , 31.        , 28.        ,
       29.        , 55.67215569, 20.        , 19.        , 17.        ,
       11.        , 18.        , 13.        , 14.        ,  4.        ,
        8.        ,  7.        , 16.        , 15.        , 10.        ,
       12.        ,  9.        ,  6.        ,  2.        ,  1.        ,
       43.        , 38.        , 40.        , 44.        , 41.        ,
       37.        , 39.        , 42.        , 35.        , 34.        ,
       33.        , 36.        , 53.        , 51.        , 54.        ,
       45.        , 55.        , 48.        , 52.        , 49.        ,
       56.        , 50.        , 47.        , 46.        , 58.        ,
       68.        , 59.        , 62.        , 65.        , 67.        ,
       64.        , 60.        , 61.        , 66.        , 57.        ,
       63.        , 73.        , 79.        , 78.        , 74.  

<br/>
 <h3><b> In handling the KM </b></h3>

*   In this case, ?? is present.
*   Replace ?? with some random number (because we need to convert into float).
*   Convert object type to float.
*   Replace random number with NaN.
*   Now, Replace NaN with mean of the entire column.

<br/>

In [60]:
# handling KM

display(datasets['KM'].unique())

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [61]:
# replace '??' with -99999
datasets['KM'] = datasets['KM'].replace('??',-99999)
datasets['KM']

0        46986
1        72937
2        41711
3        48000
4        38500
         ...  
1431     20544
1432    -99999
1433     17016
1434    -99999
1435         1
Name: KM, Length: 1436, dtype: object

In [62]:
# convert into float

datasets["KM"] = datasets["KM"].astype(float)
datasets["KM"] = datasets['KM'].replace(-99999, np.nan)
datasets["KM"]

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...   
1431    20544.0
1432        NaN
1433    17016.0
1434        NaN
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [63]:
# replace nan with mean

datasets['KM'] = datasets['KM'].fillna(datasets['KM'].mean(skipna=True))
datasets['KM']

0       46986.000000
1       72937.000000
2       41711.000000
3       48000.000000
4       38500.000000
            ...     
1431    20544.000000
1432    68647.239972
1433    17016.000000
1434    68647.239972
1435        1.000000
Name: KM, Length: 1436, dtype: float64

<br/>
 <h3><b> In handling the FuelType </b></h3>

*   First check that which values are more in column.
*   In this case, Petrol has more values.
*   So, we replace nan with Petrol.

<br/>

In [64]:
# handling 'FuelType'

print(datasets['FuelType'].unique())
print(datasets['FuelType'].value_counts())

['Diesel' nan 'Petrol' 'CNG']
Petrol    1177
Diesel     144
CNG         15
Name: FuelType, dtype: int64


In [65]:
# replaing nan with petrol

datasets['FuelType'] = datasets['FuelType'].fillna('Petrol')
datasets['FuelType']

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...  
1431    Petrol
1432    Petrol
1433    Petrol
1434    Petrol
1435    Petrol
Name: FuelType, Length: 1436, dtype: object

<br/>
 <h3><b> In handling the HP </b></h3>

*   In this case, ???? is present.
*   Replace ???? with some random number (because we need to convert into float).
*   Convert object type to float.
*   Replace random number with NaN.
*   Now, Replace NaN with mean of the entire column.

<br/>

In [66]:
display(datasets['HP'].unique())

array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [67]:
datasets['HP'] = datasets['HP'].replace('????',-99999)
datasets['HP']

0        90
1        90
2        90
3        90
4        90
       ... 
1431     86
1432     86
1433     86
1434     86
1435    110
Name: HP, Length: 1436, dtype: object

In [68]:
# convert into float

datasets["HP"] = datasets["HP"].astype(float)
datasets["HP"] = datasets['HP'].replace(-99999, np.nan)
datasets["HP"]

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
        ...  
1431     86.0
1432     86.0
1433     86.0
1434     86.0
1435    110.0
Name: HP, Length: 1436, dtype: float64

In [69]:
datasets['HP'] = datasets['HP'].fillna(datasets['HP'].mean(skipna=True))
print(datasets['HP'])

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
        ...  
1431     86.0
1432     86.0
1433     86.0
1434     86.0
1435    110.0
Name: HP, Length: 1436, dtype: float64


<br/>
 <h3><b> In handling the MetColor </b></h3>

*   In this case, there can be only two values 0 and 1.
*   So, first we check that null values are present or not.
*   Null values are replaced with '1' because of more occcurence in dataset.

<br/>

In [70]:
display(datasets['MetColor'].unique())
print(datasets['MetColor'].value_counts())

array([ 1., nan,  0.])

1.0    868
0.0    418
Name: MetColor, dtype: int64


In [71]:
datasets['MetColor'] = datasets['MetColor'].fillna(1)
datasets['MetColor']

0       1.0
1       1.0
2       1.0
3       0.0
4       0.0
       ... 
1431    1.0
1432    0.0
1433    0.0
1434    1.0
1435    0.0
Name: MetColor, Length: 1436, dtype: float64

<br/>
 <h3><b> In handling the Automatic </b></h3>

*   First, we check null values are present or not.
*   In this case, null values are not present.

<br/>

In [72]:
display(datasets['Automatic'].unique())

array([0, 1])

<br/>
 <h3><b> In handling the CC </b></h3>

*   First, we check null values are present or not.
*   In this case, null values are not present.

<br/>

In [73]:
display(datasets['CC'].unique())

array([2000, 1800, 1900, 1600, 1400, 1598, 1995, 1398, 1300, 1587, 1975,
       1332])

<br/>
 <h3><b> In handling the Doors </b></h3>

*   We try to check which values are present.
*   In this case, for some of the row values are in form of word.
*   We declare the mapping for word. Replace word with corresponding value.
*   Then, convert from object type to int type.
*   Checking for null values which are not present in this case.

<br/>

In [74]:
display(datasets['Doors'].unique())

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [75]:
mapping = {'three':'3','four':'4','five':'5'}
datasets['Doors'] = datasets['Doors'].replace(mapping)

In [76]:
datasets['Doors'] = datasets['Doors'].astype(int)
display(datasets['Doors'].unique())

array([3, 5, 4, 2])

## Handling Missing values using Imputer

In [33]:
# Step 1: Import Libraries

import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 

# mount drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [34]:
# step - 2 Load data

datasets = pd.read_csv("/content/drive/MyDrive/ML LAB/Exercise-CarData.csv")

print("\nDatasets: \n", datasets)
print("\n Statstics: \n", datasets.describe())


Datasets: 
       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

 Statstics: 
         Unnamed: 0         Price  ...           CC      Weight
count  

In [35]:
# Step 3: Seprate Input and Output attributes

# all rows and all cols except first
X = datasets.loc[:, datasets.columns != "Price"].values

# take only output column
Y = datasets.loc[:, datasets.columns == "Price"].values

print("Input: \n", X)
print("\n\nOutput: \n", Y)

Input: 
 [[0 23.0 '46986' ... 2000 'three' 1165]
 [1 23.0 '72937' ... 2000 '3' 1165]
 [2 24.0 '41711' ... 2000 '3' 1165]
 ...
 [1433 nan '17016' ... 1300 '3' 1015]
 [1434 70.0 '??' ... 1300 '3' 1015]
 [1435 76.0 '1' ... 1600 '5' 1114]]


Output: 
 [[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]


In [36]:
# drop row who has value null in all columns.

datasets.dropna(axis = 0, how = 'all',inplace = True)
print("\nNew Data :",datasets)


New Data :       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]


In [52]:
# all rows and all cols except first
X = datasets.loc[:, datasets.columns != "Price"].values

# take only output column
Y = datasets.loc[:, datasets.columns == "Price"].values

In [77]:
imputer = SimpleImputer(missing_values = np.nan,strategy = "mean")

# performing for 'Age' column.
imputer = imputer.fit(X[:, 1:2])

X[:, 1:2] = imputer.transform(X[:, 1:2]) 

# filling the missing value with mean 
print("\n\nNew Input with Mean Value for NaN : \n\n", X[:, 1:2]) 



New Input with Mean Value for NaN : 

 [[23.0]
 [23.0]
 [24.0]
 ...
 [55.67215568862275]
 [70.0]
 [76.0]]
