<h1> <b> Lab - 3 </b> </h1>
<br>
<br>

# Exercises on Dataset1

In [1]:
# import necessary modules
import numpy as np
import pandas as pd
from sklearn import preprocessing

# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
# read the data

df = pd.read_csv("/content/drive/MyDrive/ML LAB/Dataset1_Lab_3.csv")
df

Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N

In [27]:
# see unique value of each features

print(df["Outlook"].unique())
print("\n", df["Temp"].unique())
print("\n", df["Humidity"].unique())
print("\n", df["Wind"].unique())
print("\n", df["Play"].unique())

['R' 'O' 'S']

 ['H' 'M' 'C']

 ['Normal' 'High' 'Low']

 ['F' 'T']

 ['N' 'Y']


In [28]:
# create label encode object for label encoding
label_encoder = preprocessing.LabelEncoder()

df["Outlook"] = label_encoder.fit_transform(df["Outlook"])
df["Outlook"].unique()

array([1, 0, 2])

In [29]:
df["Temp"] = label_encoder.fit_transform(df["Temp"])
df["Temp"].unique()

array([1, 2, 0])

In [30]:
df["Humidity"] = label_encoder.fit_transform(df["Humidity"])
df["Humidity"].unique()

array([2, 0, 1])

In [31]:
df["Wind"] = label_encoder.fit_transform(df["Wind"])
df["Wind"].unique()

array([0, 1])

In [32]:
df["Play"] = label_encoder.fit_transform(df["Play"])
df["Play"].unique()

array([0, 1])

In [33]:
#import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

datasets = df
datasets

Outlook  Temp  Humidity  Wind  Play
0         1     1         2     0     0
1         1     1         0     1     0
2         0     1         2     0     1
3         2     2         2     0     1
4         2     0         2     0     1
5         2     0         1     1     0
6         0     0         2     1     1
7         1     2         2     0     0
8         1     0         1     0     1
9         2     2         0     0     1
10        1     2         0     1     1
11        0     2         1     1     1
12        0     1         2     0     1
13        2     2         2     1     0

In [34]:
# separate the features from the class label
features = datasets.loc[:, datasets.columns != 'Play'].values

#take only class label
target = datasets.loc[:, datasets.columns == 'Play'].values
target = target.reshape((-1,target.shape[0]))[0]    # do reshape

print("Features: \n", features)
print("\n\nTarget: \n", target)


Features: 
 [[1 1 2 0]
 [1 1 0 1]
 [0 1 2 0]
 [2 2 2 0]
 [2 0 2 0]
 [2 0 1 1]
 [0 0 2 1]
 [1 2 2 0]
 [1 0 1 0]
 [2 2 0 0]
 [1 2 0 1]
 [0 2 1 1]
 [0 1 2 0]
 [2 2 2 1]]


Target: 
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [35]:
# train and test data -> Train and test 80% - 20%

data_train, data_test, target_train, target_test = train_test_split(features,
target, test_size = 0.20, random_state = 46)

In [36]:
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [37]:
print(target_test, "\n", target_pred)

[0 1 1] 
 [1 1 1]


In [38]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy
print("Accuracy:", metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.6666666666666666


In [39]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(target_test, target_pred)

array([[0, 1],
       [0, 2]])

In [40]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average = None, labels = np.unique(target_pred))

recall = recall_score(target_test, target_pred, average = None, labels = np.unique(target_pred))

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.66666667]
recall: [1.]


<h2> <b> Q.1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?</b> </h2>

In [24]:
# R - 1
# Mild - 2
# Normal - 2
# False - 0

predicted_output_1 = gnb.predict([[1, 2, 2, 0]])
predicted_output_1

array([1])

<h2> <b> Q.2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?</b> </h2>

In [25]:
# sunny - 2
# cool- 0
# high - 0
# true - 1

predicted_output = gnb.predict([[2, 0, 0, 1]])
predicted_output

array([1])

# Exercises on breast cancer wisconsin dataset

In [43]:
# import necessary modules
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import datasets

In [44]:
# load the data

cancer = datasets.load_breast_cancer()

In [45]:
# take features

features = cancer.data
features = pd.DataFrame(features)
features.head()

0      1       2       3   ...      26      27      28       29
0  17.99  10.38  122.80  1001.0  ...  0.7119  0.2654  0.4601  0.11890
1  20.57  17.77  132.90  1326.0  ...  0.2416  0.1860  0.2750  0.08902
2  19.69  21.25  130.00  1203.0  ...  0.4504  0.2430  0.3613  0.08758
3  11.42  20.38   77.58   386.1  ...  0.6869  0.2575  0.6638  0.17300
4  20.29  14.34  135.10  1297.0  ...  0.4000  0.1625  0.2364  0.07678

[5 rows x 30 columns]

In [46]:
# take target

target = cancer.target

print(cancer.target_names)

print("\n", target)

['malignant' 'benign']

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1


<h2> <b> As target labels are alraedy encoded no need of OneHotEncoding </b> </h2>

In [47]:
from sklearn.model_selection import train_test_split

feature_train, feature_test, target_train, target_test = train_test_split(features.to_numpy(),target , test_size = 0.40, random_state=46)

In [48]:
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(feature_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(feature_test)

In [49]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy
print("Accuracy:", metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9473684210526315


In [50]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(target_test, target_pred)

array([[ 74,   9],
       [  3, 142]])

In [51]:
precision = precision_score(target_test, target_pred, average=None)

recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.96103896 0.94039735]
recall: [0.89156627 0.97931034]
