<h1> <b> Lab - 2 </b> </h1>
<h2> <b> Excersise on Data Transformation </b> </h1>
<br/>


In [ ]:
# Step 1: Import Libraries

import numpy as np 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# mount drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# step - 2 Load data

datasets = pd.read_csv("/content/drive/MyDrive/ML LAB/Exercise-CarData.csv")

print("\nDatasets: \n", datasets)
print("\n Statstics: \n", datasets.describe())


Datasets: 
       Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

 Statstics: 
         Unnamed: 0         Price  ...           CC      Weight
count  

In [ ]:
# Step 3: Seprate Input and Output attributes

# all rows and all cols except first
X = datasets.loc[:, datasets.columns != "Price"].values

# take only output column
Y = datasets.loc[:, datasets.columns == "Price"].values

print("Input: \n", X)
print("\n\nOutput: \n", Y)

Input: 
 [[0 23.0 '46986' ... 2000 'three' 1165]
 [1 23.0 '72937' ... 2000 '3' 1165]
 [2 24.0 '41711' ... 2000 '3' 1165]
 ...
 [1433 nan '17016' ... 1300 '3' 1015]
 [1434 70.0 '??' ... 1300 '3' 1015]
 [1435 76.0 '1' ... 1600 '5' 1114]]


Output: 
 [[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]


<br/>

<h3> <b> Perfomring Scaling on 'Age' column </b> </h3>

*   Fetch 'Age' column from datasets, put into X_new.
*   Fill null values with mean of the column.
*   Update X_new with new values of 'Age'.
*   Define the scaler and do scaling on 'Age' column.

<br/>

In [ ]:
# take 'Age' Column
X_new = datasets.iloc[:, 2:3]
print(X_new)

       Age
0     23.0
1     23.0
2     24.0
3     26.0
4     30.0
...    ...
1431   NaN
1432  72.0
1433   NaN
1434  70.0
1435  76.0

[1436 rows x 1 columns]


In [ ]:
# fill null values

datasets['Age'].fillna(datasets['Age'].mean(skipna=True), inplace=True)
datasets['Age'].unique()

array([23.        , 24.        , 26.        , 30.        , 32.        ,
       27.        , 25.        , 22.        , 31.        , 28.        ,
       29.        , 55.67215569, 20.        , 19.        , 17.        ,
       11.        , 18.        , 13.        , 14.        ,  4.        ,
        8.        ,  7.        , 16.        , 15.        , 10.        ,
       12.        ,  9.        ,  6.        ,  2.        ,  1.        ,
       43.        , 38.        , 40.        , 44.        , 41.        ,
       37.        , 39.        , 42.        , 35.        , 34.        ,
       33.        , 36.        , 53.        , 51.        , 54.        ,
       45.        , 55.        , 48.        , 52.        , 49.        ,
       56.        , 50.        , 47.        , 46.        , 58.        ,
       68.        , 59.        , 62.        , 65.        , 67.        ,
       64.        , 60.        , 61.        , 66.        , 57.        ,
       63.        , 73.        , 79.        , 78.        , 74.  

In [ ]:
# update X_new

X_new = datasets.iloc[:, 2:3]
print(X_new)

            Age
0     23.000000
1     23.000000
2     24.000000
3     26.000000
4     30.000000
...         ...
1431  55.672156
1432  72.000000
1433  55.672156
1434  70.000000
1435  76.000000

[1436 rows x 1 columns]


In [ ]:
# Step 4 : Perform scaling on 'Age'

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_new)
print("\nScaled X : \n", X_scaled)


Scaled X : 
 [[0.27848101]
 [0.27848101]
 [0.29113924]
 ...
 [0.6920526 ]
 [0.87341772]
 [0.94936709]]


In [ ]:
std = StandardScaler()
X_std = std.fit_transform(X_new)
print("\n\nStandardized X : \n", X_std)



Standardized X : 
 [[-1.82280225]
 [-1.82280225]
 [-1.76701156]
 ...
 [ 0.        ]
 [ 0.79936038]
 [ 1.13410455]]
